language: node_js
node_js: "10"
cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install --prefix tests/app/
before_script:
  - npm run build
  - nohup npm start --prefix tests/app/ 2>/dev/null 1>/dev/null &
script:
  - npm test
